### ISSUE TITLE
Server "crashes", intermittent

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#1058]
For a while now we've been getting server "crashes" (more like time outs where our watchdog script force reboots it) and the backtrace always looks like this. We've logged most NwNx activities but can't find a clear pattern. Anyone has any idea what it could be? And if not, any other more advanced information you'd need?

> [New LWP 12207]
> [New LWP 12210]
> [New LWP 12209]
> [New LWP 12211]
> [New LWP 12213]
> [New LWP 12222]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Program terminated with signal SIGQUIT, Quit.
> #0  0x000055903ee80b96 in ?? ()
> [Current thread is 1 (Thread 0x7f477662a200 (LWP 12207))]
> #0  0x000055903ee80b96 in ?? ()
> #1  0x000055903ee8f19d in ?? ()
> #2  0x000055903f04c1ef in ?? ()
> #3  0x00007f4776c858ca in NWNXLib::Hooking::FunctionHook::CallOriginal<int, CServerExoAppInternal*> (this=0x55904768bee0)
>     at /home/potm/nwnx2_EE/unified/NWNXLib/./Hooking/FunctionHook.hpp:21
> #4  NWNXLib::Services::HooksImpl::HookLandingHolderShared::HookLanding<3162480ul, int, CServerExoAppInternal*> (arg1=0x5590477a9ba0)
>     at /home/potm/nwnx2_EE/unified/NWNXLib/./Services/Hooks/HooksImpl.hpp:114
> #5  0x000055903ee235d5 in ?? ()
> #6  0x00007f47766520b3 in __libc_start_main (main=0x55903ee22660, argc=37, 
>     argv=0x7ffe77fdb368, init=<optimized out>, fini=<optimized out>, 
>     rtld_fini=<optimized out>, stack_end=0x7ffe77fdb358)
>     at ../csu/libc-start.c:308
> #7  0x000055903ee26afa in _start ()

**Comment by Daztek** [comment]
Closing this since it's a really old issue from many years ago. If it's actually still happening, feel free to open a new issue!
